# Tema remoto
theme: minimal-mistakes-jekyll

# Plugins requeridos por Minimal Mistakes
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-sitemap

# Configuración del skin
minimal_mistakes_skin: "dark"

# Autor
author:
  name: "0xzig0x"
  avatar: "/assets/images/b.jpg"
  bio: "Apasionado y estudiante de ciberseguridad especializado en Red Team y Pentesting"
  location: "Colombia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/0xzig0x"
    - label: "0xzig0x@proton.me"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:0xzig0x@proton.me"
    - label: "0xbin0x"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.com/users/0xbin0x"

# Archivos de categorías y tags
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  pages:
    output: true
    permalink: /:path/

